# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: City of Austin Design, Technology, and Innovation Fellows
email: innovationfellows@austintexas.gov
description: >
  The City of Austin’s Design, Technology, and Innovation Fellows program provides
  an opportunity for Austin’s passionate and civic-minded designers and developers to bring the
  principles, values, and practices of the technology sector into government.
baseurl:
url: http://projects.austintexas.io
twitter:
  username: civiqueso
medium_url: https://medium.com/city-of-austin-design-technology-innovation
zilker_theme: light
# dark is the default, light will also work.

# Build settings
markdown: kramdown
collections:
  projects:
    title: Projects
    output: true
    permalink: /:collection/:path/

defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: 'sidebar-page'
    nav_from_collection: 'projects'
    image_path: '/assets/img/projects/project-tile-placeholder.jpg'

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Jekyll SEO Tag
# See https://github.com/jekyll/jekyll-seo-tag

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: assets/stylesheets/
permalink: pretty
exclude:
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - npm-debug.log
  - /screenshots
  - /assets/stylesheets/bourbon
  - /assets/stylesheets/bourbon-neat
  - /assets/uswds/stylesheets
  - /assets/uswds/js
  - .bundle
  - /vendor
  - _bourbon
  - _bourbon-neat
  - _uswds
